export const leaderboard = [
    {"name": "Athul U","refCode": "XZW03", "score": 1220},
    {"name": "Anjitha Vinayan", "refCode": "U9EI2", "score": 1176},
    {"name": "Bilal N", "refCode": "GAUZ0", "score": 828},
    {"name": "Mathson Beshy", "refCode": "ZOV6E", "score": 396},
    {"name": "Aaliyah Rauf", "refCode": "PE5JC", "score": 170},
    {"name": "B R KRISHNANUNNI", "refCode": "X1YBA", "score": 162},
    {"name": "Akarsha Davis", "refCode": "42UWP", "score": 145},
    {"name": "Mohammed Shan", "refCode": "Z7DX1", "score": 139},
    {"name": "Muhammed Afsal", "refCode": "PEMAT", "score": 105},
    {"name": "Juhana Sherin T M", "refCode": "I9EVG", "score": 95},
    {"name": "Anu Anna S", "refCode": "32170", "score": 95},
    {"name": "K E NANDAGOPAL", "refCode": "W51A2", "score": 90},
    {"name": "Fahmin Fayas A.K", "refCode": "01OLR", "score": 89},
    {"name": "Farhana Fathima Ayoob", "refCode": "9NJ64", "score": 80},
    {"name": "Ann S S", "refCode": "BV83W", "score": 80},
    {"name": "Naslu KK", "refCode": "9827N", "score": 80},
    {"name": "Albert George", "refCode": "MQVEH", "score": 73},
    {"name": "Muhammed Rashil K", "refCode": "PH438", "score": 62},
    {"name": "Namitha Manoj", "refCode": "QHC76", "score": 53},
    {"name": "John Varghese Benny",  "refCode": "N6PFY", "score": 51},
  ];