export const leaderboard = [
  { refCode: "4DWXT", name: "Mohammed Ashmil", score: 17200 },
  { refCode: "XZW03", name: "Athul U", score: 14980 },
  { refCode: "U9EI2", name: "Anjitha Vinayan", score: 8534 },
  { refCode: "PEMAT", name: "Muhammed Afsal", score: 6519 },
  { refCode: "TFM9D", name: "Muhammed Faizal S", score: 6480 },
  { refCode: "A8HW3", name: "Muhammad Alfas", score: 5840 },
  { refCode: "RVFI9", name: "Allen Binu", score: 5440 },
  { refCode: "SP96C", name: "Sithara R S", score: 4854 },
  { refCode: "XOVB5", name: "Vian Vinod", score: 4505 },
  { refCode: "BV83W", name: "Ann S S", score: 4380 },
  { refCode: "0SRG5", name: "Adil A", score: 4025 },
  { refCode: "QUK8Y", name: "Muhammad Luthufi TP", score: 4000 },
  { refCode: "6O4EU", name: "Jerry Sanju Joanes", score: 3920 },
  { refCode: "GAUZ0", name: "Bilal N", score: 3709 },
  { refCode: "X1YBA", name: "B R Krishnanunni", score: 3616 },
  { refCode: "01OLR", name: "Fahmin Fayas. A.K", score: 3602 },
  { refCode: "ZOV6E", name: "Mathson Beshy", score: 3356 },
  { refCode: "NET0J", name: "Bagninesh M B", score: 2350 },
  { refCode: "E0UW9", name: "Ahammed Sahal A U", score: 2320 },
  { refCode: "C19D5", name: "Sreemaya K Rajan", score: 1784 },
  { refCode: "JGRZI", name: "Felix Johny", score: 1705 },
  { refCode: "PE5JC", name: "Aaliyah Rauf", score: 1618 },
  { refCode: "42UWP", name: "Akarsha Davis", score: 1544 },
  { refCode: "X91YV", name: "Muhammed Salah", score: 1293 },
  { refCode: "YT35X", name: "Krishnaprasad P", score: 1225 },
  { refCode: "YS3AD", name: "Shain Shaji", score: 830 },
  { refCode: "EK91V", name: "Kashyap Ajaikumar", score: 803 },
  { refCode: "GQW6K", name: "Navaneeth C L", score: 800 },
  { refCode: "WJX8U", name: "Megha R", score: 753 },
  { refCode: "PXKUO", name: "Aleena Rose Antony", score: 745 },
];
