export const leaderboard = [
    {"name": "Athul U", "college": "Sree Buddha College of Engineering, Pattoor", "refCode": "XZW03", "score": 1220},
    {"name": "Anjitha Vinayan", "college": "KMEA Engineering College", "refCode": "U9EI2", "score": 1176},
    {"name": "Bilal N", "college": "Younus College of Engineering and Technology,Kollam", "refCode": "GAUZ0", "score": 828},
    {"name": "Mathson Beshy", "college": "Ilahia College of Engineering and Technology", "refCode": "ZOV6E", "score": 396},
    {"name": "Aaliyah Rauf", "college": "St. Teresa's College(Autonomous), Ernakulam", "refCode": "PE5JC", "score": 170},
    {"name": "B R KRISHNANUNNI", "college": "Christ Nagar College, Maranalloor", "refCode": "X1YBA", "score": 162},
    {"name": "Akarsha Davis", "college": "Sahrdaya College of Engineering and Technology", "refCode": "42UWP", "score": 145},
    {"name": "Mohammed Shan", "college": "School of Engineering CUSAT", "refCode": "Z7DX1", "score": 139},
    {"name": "Muhammed Afsal", "college": "Travancore Engineering College", "refCode": "PEMAT", "score": 105},
    {"name": "Juhana Sherin T M", "college": "Sahrdaya College of Engineering and Technology", "refCode": "I9EVG", "score": 95},
    {"name": "Anu Anna S", "college": "Carmel Polytechnic College Alappuzha", "refCode": "32170", "score": 95},
    {"name": "K E NANDAGOPAL", "college": "LBS College of Engineering", "refCode": "W51A2", "score": 90},
    {"name": "Fahmin Fayas A.K", "college": "Malabar College of Advanced Studies, Vengara", "refCode": "01OLR", "score": 89},
    {"name": "Farhana Fathima Ayoob", "college": "CMS College Kottayam", "refCode": "9NJ64", "score": 80},
    {"name": "Ann S S", "college": "University College of Engineering, Kariavattom", "refCode": "BV83W", "score": 80},
    {"name": "Naslu KK", "college": "AWH Engineering College Kozhikode", "refCode": "9827N", "score": 80},
    {"name": "Albert George", "college": "Government Engineering College Idukki", "refCode": "MQVEH", "score": 73},
    {"name": "Muhammed Rashil K", "college": "Majlis Arts & Science College Valanjery", "refCode": "PH438", "score": 62},
    {"name": "Namitha Manoj", "college": "School of Engineering, CUSAT", "refCode": "QHC76", "score": 53},
    {"name": "John Varghese Benny", "college": "NSS College of Engineering Palakkad", "refCode": "N6PFY", "score": 51},
  ];